version: '3.4'
services:
  fullstack-sqlserver:
    image: fullstack-sqlserver-image
    build: 
      context: ./SQLSERVER
      dockerfile: Dockerfile
    restart: always
    container_name: fullstack-sqlserver-container
    environment:
      SA_PASSWORD: DEMODataBase15845!
      ACCEPT_EULA: Y
    ports:
    - "1433:1433"
    expose: 
    - "1433"
    networks:
      - fullstack-network
  fullstack-dotnet:
    image: fullstack-dotnet-image
    build:
      context: ./WebApp
      dockerfile: ./REST_Services/Dockerfile
    restart: always
    container_name: fullstack-dotnet-container
    ports:
    - "8080:8080"
    depends_on:
      - fullstack-sqlserver
    networks:
      - fullstack-network 
  fullstack-angular:
    depends_on:
      - fullstack-dotnet
    image: fullstack-angular-image
    build:
      context: ./FrontEndWebAppAngular
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    restart: always
    container_name: fullstack-angular-container
    networks:
      - fullstack-network   
networks:
  fullstack-network:
    driver: bridge